### PR TITLE
add snippets for mobile platform projects

### PR DESCRIPTION
**Pull request by guibas741**
## Motivation
This is a proposal to have snippets with some common boilerplate on the mobile platform projects. 

### Mobile platform use case (mpuc)
https://user-images.githubusercontent.com/24190696/115023139-c016cc00-9e94-11eb-86b4-b655f88593eb.mov 

### Mobile platform component test (mpct)
https://user-images.githubusercontent.com/24190696/115023320-02d8a400-9e95-11eb-954b-bd5ce0d75baa.mov

### Mobile platform test unit (mpit) 
https://user-images.githubusercontent.com/24190696/115023430-2ac80780-9e95-11eb-93f4-5b7781e4cfa1.mov

### Mobile platform component (mpc)
https://user-images.githubusercontent.com/24190696/115023475-3ca9aa80-9e95-11eb-848b-689c5dc2d5a7.mov

### CODE REVIEW

**Review by ruimartin — APPROVED** [review]
Top! 🥇

**Review by gutofoletto — APPROVED** [review]
nice contribution!

**Review by ruimartin — APPROVED** [review]

**Review by barbosa — COMMENTED** [review]
Nice work, @guibas741 💥 

Would you add a CHANGELOG entry before merging it? It will later be used to publish a new version to VSCode's markeplace.

**Review by lenoirzamboni — APPROVED** [review]
Nice!  🚀

**Comment by guibas741** [comment]
> Nice work, @guibas741 💥
> 
> Would you add a CHANGELOG entry before merging it? It will later be used to publish a new version to VSCode's markeplace.

thanks @barbosa, I added the changelog. Can I create a release tag after the merge?

**Comment by barbosa** [comment]
@guibas741 sure thing! Thanks, Gui.

**Review by barbosa — APPROVED** [review]

**Pull request merged**
